### ISSUE TITLE
Illuminatti?

### ISSUE THREAD

**Issue by Asasinovici** [leryss/VulkanTriangle#1]
I think the 3 sided polygon you have created is oddly resemblant to the pyramid of masonic origin. Can you please confirm this? It's very important for me as a part of the "Illuminatti society" to confirm the origin of this shape for I wish to use it as undeniable evidence regarding the existence of the aforementioned organization.

**Comment by leryss** [comment]
Hello,
A triangle is a polygon with three edges and three vertices. It is one of the basic shapes in geometry. A triangle with vertices A, B, and C is denoted △ A B C.

In Euclidean geometry any three points, when non-collinear, determine a unique triangle and simultaneously, a unique plane (i.e. a two-dimensional Euclidean space). In other words, there is only one plane that contains that triangle, and every triangle is contained in some plane. If the entire geometry is only the Euclidean plane, there is only one plane and all triangles are contained in it; however, in higher-dimensional Euclidean spaces, this is no longer true. This article is about triangles in Euclidean geometry, and in particular, the Euclidean plane, except where otherwise noted. 

Triangles can be classified according to the lengths of their sides:

    An equilateral triangle has all sides the same length. An equilateral triangle is also a regular polygon with all angles measuring 60°.[1]
    An isosceles triangle has two sides of equal length.[note 1][2] An isosceles triangle also has two angles of the same measure, namely the angles opposite to the two sides of the same length; this fact is the content of the isosceles triangle theorem, which was known by Euclid. Some mathematicians define an isosceles triangle to have exactly two equal sides, whereas others define an isosceles triangle as one with at least two equal sides.[2] The latter definition would make all equilateral triangles isosceles triangles. The 45–45–90 right triangle, which appears in the tetrakis square tiling, is isosceles.
    A scalene triangle has all its sides of different lengths.[3] Equivalently, it has all angles of different measure.

Triangles can also be classified according to their internal angles, measured here in degrees.

    A right triangle (or right-angled triangle, formerly called a rectangled triangle) has one of its interior angles measuring 90° (a right angle). The side opposite to the right angle is the hypotenuse, the longest side of the triangle. The other two sides are called the legs or catheti[4] (singular: cathetus) of the triangle. Right triangles obey the Pythagorean theorem: the sum of the squares of the lengths of the two legs is equal to the square of the length of the hypotenuse: a2 + b2 = c2, where a and b are the lengths of the legs and c is the length of the hypotenuse. Special right triangles are right triangles with additional properties that make calculations involving them easier. One of the two most famous is the 3–4–5 right triangle, where 32 + 42 = 52. In this situation, 3, 4, and 5 are a Pythagorean triple. The other one is an isosceles triangle that has 2 angles that each measure 45 degrees.
    Triangles that do not have an angle measuring 90° are called oblique triangles.
    A triangle with all interior angles measuring less than 90° is an acute triangle or acute-angled triangle. If c is the length of the longest side, then a2 + b2 > c2, where a and b are the lengths of the other sides.
    A triangle with one interior angle measuring more than 90° is an obtuse triangle or obtuse-angled triangle. If c is the length of the longest side, then a2 + b2 < c2, where a and b are the lengths of the other sides.
    A triangle with an interior angle of 180° (and collinear vertices) is degenerate.
    A right degenerate triangle has collinear vertices, two of which are coincident.

A triangle that has two angles with the same measure also has two sides with the same length, and therefore it is an isosceles triangle. It follows that in a triangle where all angles have the same measure, all three sides have the same length, and such a triangle is therefore equilateral. 

There are thousands of different constructions that find a special point associated with (and often inside) a triangle, satisfying some unique property: see the article Encyclopedia of Triangle Centers for a catalogue of them. Often they are constructed by finding three lines associated in a symmetrical way with the three sides (or vertices) and then proving that the three lines meet in a single point: an important tool for proving the existence of these is Ceva's theorem, which gives a criterion for determining when three such lines are concurrent. Similarly, lines associated with a triangle are often constructed by proving that three symmetrically constructed points are collinear: here Menelaus' theorem gives a useful general criterion. In this section just a few of the most commonly encountered constructions are explained. 

The area within any closed curve, such as a triangle, is given by the line integral around the curve of the algebraic or signed distance of a point on the curve from an arbitrary oriented straight line L. Points to the right of L as oriented are taken to be at negative distance from L, while the weight for the integral is taken to be the component of arc length parallel to L rather than arc length itself.

This method is well suited to computation of the area of an arbitrary polygon. Taking L to be the x-axis, the line integral between consecutive vertices (xi,yi) and (xi+1,yi+1) is given by the base times the mean height, namely (xi+1 − xi)(yi + yi+1)/2. The sign of the area is an overall indicator of the direction of traversal, with negative area indicating counterclockwise traversal. The area of a triangle then falls out as the case of a polygon with three sides.

While the line integral method has in common with other coordinate-based methods the arbitrary choice of a coordinate system, unlike the others it makes no arbitrary choice of vertex of the triangle as origin or of side as base. Furthermore, the choice of coordinate system defined by L commits to only two degrees of freedom rather than the usual three, since the weight is a local distance (e.g. xi+1 − xi in the above) whence the method does not require choosing an axis normal to L.

When working in polar coordinates it is not necessary to convert to Cartesian coordinates to use line integration, since the line integral between consecutive vertices (ri,θi) and (ri+1,θi+1) of a polygon is given directly by riri+1sin(θi+1 − θi)/2. This is valid for all values of θ, with some decrease in numerical accuracy when |θ| is many orders of magnitude greater than π. With this formulation negative area indicates clockwise traversal, which should be kept in mind when mixing polar and cartesian coordinates. Just as the choice of y-axis (x = 0) is immaterial for line integration in cartesian coordinates, so is the choice of zero heading (θ = 0) immaterial here. 

I hope this has cleared any misunderstandings about the polygon we so call triangle. Thank you and have a nice day !
